name: Snyk monitor
on:
  workflow_dispatch:
  schedule:
    - cron: '49 1 * * *'
permissions:
  contents: read
jobs:
  snyk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repository: folio-org/platform-lsp
            branch: R1-2025
          - repository: folio-org/platform-lsp
            branch: snapshot
          - repository: folio-org/platform-complete
            branch: R1-2025-okapi
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ matrix.repository }}
          ref: ${{ matrix.branch }}
      - uses: actions/setup-node@v6
        with:
          node-version: '*'
          cache: yarn
      - run: 'yarn config set @folio:registry https://repository.folio.org/repository/npm-folio/'
      - run: yarn install
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK }}
        with:
          command: monitor
          args: --target-reference=${{ matrix.branch }}
