name: Snyk monitor
on: workflow_dispatch
permissions:
  contents: read
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'folio-org/platform-lsp'
          ref: 'R1-2025'
      - run: 'yarn config set @folio:registry https://repository.folio.org/repository/npm-folio/'
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=julianladisch
